import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins,Bangers,Atma,Lobster} from "next/font/google";
import "./globals.css";
import Providers from './providers';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const bangers = Bangers({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bangers',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const atma = Atma({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-atma',
});
const lobster = Lobster({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lobster',
});
const poppins = Poppins({
  weight: ['300', '400', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Queryly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
<html lang="en">
        <head>  
          <title>Queryly</title>
          <link rel="icon" href="/queryhub-logo-1.png" type="image/png" />
          <script src="./node_modules/preline/dist/preline.js"></script>
        </head>
        <body
  className={`${geistSans.variable} ${geistMono.variable} ${lobster.variable} ${poppins.variable} ${atma.variable} ${bangers.variable} antialiased`}
>

          <Providers>
          {children}
          </Providers>
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
