import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Query Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
<html lang="en">
        <head>  
          <title>Queryly</title>
          <link rel="icon" href="/queryhub-logo-1.png" type="image/png" />
          <script src="./node_modules/preline/dist/preline.js"></script>
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers>
          {children}
          </Providers>
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
